# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 17:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('depTimeString', models.CharField(blank=True, max_length=200, null=True)),
                ('maxUpperColumns', models.CharField(blank=True, max_length=500, null=True)),
                ('fromCity', models.FloatField(blank=True, null=True)),
                ('maxLowerColumns', models.CharField(blank=True, max_length=200, null=True)),
                ('maxLowerRows', models.CharField(blank=True, max_length=200, null=True)),
                ('DPInformationList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('toCity', models.CharField(blank=True, max_length=200, null=True)),
                ('maxUpperRows', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicleType', models.CharField(blank=True, max_length=200, null=True)),
                ('BPInformationList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('travelDate', models.CharField(blank=True, max_length=200, null=True)),
                ('busType', models.CharField(blank=True, max_length=200, null=True)),
                ('MPax', models.CharField(blank=True, max_length=200, null=True)),
                ('serviceName', models.CharField(blank=True, max_length=200, null=True)),
                ('seatList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('toCityId', models.CharField(blank=True, max_length=200, null=True)),
                ('operatorId', models.CharField(blank=True, max_length=200, null=True)),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('dateOFJourney', models.CharField(blank=True, max_length=200, null=True)),
                ('routeId', models.CharField(blank=True, max_length=200, null=True)),
                ('travels', models.CharField(blank=True, max_length=200, null=True)),
                ('arrTime', models.CharField(blank=True, max_length=200, null=True)),
                ('arrTimeString', models.CharField(blank=True, max_length=200, null=True)),
                ('serviceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('aes', models.CharField(blank=True, max_length=200, null=True)),
                ('mxSPrTxn', models.CharField(blank=True, max_length=200, null=True)),
                ('depTime', models.CharField(blank=True, max_length=200, null=True)),
                ('isBPMapLinkShown', models.CharField(blank=True, max_length=200, null=True)),
                ('fromCityId', models.CharField(blank=True, max_length=200, null=True)),
                ('param42', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('defaultSorting', models.CharField(blank=True, max_length=200, null=True)),
                ('amenitiesData', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripSingleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('DPList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('vt', models.CharField(blank=True, max_length=200, null=True)),
                ('busType', models.CharField(blank=True, max_length=200, null=True)),
                ('Tips', models.CharField(blank=True, max_length=200, null=True)),
                ('BsSvid', models.CharField(blank=True, max_length=200, null=True)),
                ('Sort', models.CharField(blank=True, max_length=200, null=True)),
                ('IsDPA', models.CharField(blank=True, max_length=200, null=True)),
                ('NSA', models.CharField(blank=True, max_length=200, null=True)),
                ('params42', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('serviceName', models.CharField(blank=True, max_length=200, null=True)),
                ('giry', models.CharField(blank=True, max_length=200, null=True)),
                ('RbPrefCode', models.CharField(blank=True, max_length=200, null=True)),
                ('WnSt', models.CharField(blank=True, max_length=200, null=True)),
                ('DpTm', models.CharField(blank=True, max_length=200, null=True)),
                ('IsAC', models.CharField(blank=True, max_length=200, null=True)),
                ('RtId', models.CharField(blank=True, max_length=200, null=True)),
                ('IsNAc', models.CharField(blank=True, max_length=200, null=True)),
                ('IsSpF', models.CharField(blank=True, max_length=200, null=True)),
                ('IsSlpr', models.CharField(blank=True, max_length=200, null=True)),
                ('serviceId', models.CharField(blank=True, max_length=200, null=True)),
                ('FareList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('Ament', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('OpId', models.CharField(blank=True, max_length=200, null=True)),
                ('BPList', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('IsMTE', models.CharField(blank=True, max_length=200, null=True)),
                ('Rtg', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('IsBpDpSearch', models.CharField(blank=True, max_length=200, null=True)),
                ('jDur', models.CharField(blank=True, max_length=200, null=True)),
                ('isStr', models.CharField(blank=True, max_length=200, null=True)),
                ('Tvs', models.CharField(blank=True, max_length=200, null=True)),
                ('Cmpg', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('BsSt', models.CharField(blank=True, max_length=200, null=True)),
                ('ArTm', models.CharField(blank=True, max_length=200, null=True)),
                ('tripData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferdb.TripData')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
