# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedata',
            name='fromCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
