# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferdb', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
